// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.addnewrecord;

public final class BookingMethods {
  private BookingMethods() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_postBookingReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_postBookingReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_postBookingResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_postBookingResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BookingMethods.proto\032\037google/protobuf/" +
      "timestamp.proto\"\233\001\n\016postBookingReq\022\021\n\tst" +
      "udentid\030\001 \001(\004\022\021\n\tteacherid\030\002 \001(\004\022\024\n\014inst" +
      "rumentid\030\003 \001(\004\022\017\n\007genreid\030\004 \001(\004\022,\n\010dateT" +
      "ime\030\005 \001(\0132\032.google.protobuf.Timestamp\022\016\n" +
      "\006status\030\006 \001(\t\"2\n\017postBookingResp\022\013\n\003msg\030" +
      "\001 \001(\t\022\022\n\nstatuscode\030\002 \001(\0052@\n\014ClassBookin" +
      "g\0220\n\013postBooking\022\017.postBookingReq\032\020.post" +
      "BookingRespB-\n)com.musicmantra.classbook" +
      "ing.addnewrecordP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_postBookingReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_postBookingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_postBookingReq_descriptor,
        new java.lang.String[] { "Studentid", "Teacherid", "Instrumentid", "Genreid", "DateTime", "Status", });
    internal_static_postBookingResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_postBookingResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_postBookingResp_descriptor,
        new java.lang.String[] { "Msg", "Statuscode", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
