// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.addnewrecord;

/**
 * <pre>
 *defining request message format
 * </pre>
 *
 * Protobuf type {@code postBookingReq}
 */
public  final class postBookingReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:postBookingReq)
    postBookingReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use postBookingReq.newBuilder() to construct.
  private postBookingReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private postBookingReq() {
    studentid_ = 0L;
    teacherid_ = 0L;
    instrumentid_ = 0L;
    genreid_ = 0L;
    status_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private postBookingReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            studentid_ = input.readUInt64();
            break;
          }
          case 16: {

            teacherid_ = input.readUInt64();
            break;
          }
          case 24: {

            instrumentid_ = input.readUInt64();
            break;
          }
          case 32: {

            genreid_ = input.readUInt64();
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateTime_ != null) {
              subBuilder = dateTime_.toBuilder();
            }
            dateTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateTime_);
              dateTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.musicmantra.classbooking.addnewrecord.BookingMethods.internal_static_postBookingReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.musicmantra.classbooking.addnewrecord.BookingMethods.internal_static_postBookingReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.musicmantra.classbooking.addnewrecord.postBookingReq.class, com.musicmantra.classbooking.addnewrecord.postBookingReq.Builder.class);
  }

  public static final int STUDENTID_FIELD_NUMBER = 1;
  private long studentid_;
  /**
   * <code>uint64 studentid = 1;</code>
   */
  public long getStudentid() {
    return studentid_;
  }

  public static final int TEACHERID_FIELD_NUMBER = 2;
  private long teacherid_;
  /**
   * <code>uint64 teacherid = 2;</code>
   */
  public long getTeacherid() {
    return teacherid_;
  }

  public static final int INSTRUMENTID_FIELD_NUMBER = 3;
  private long instrumentid_;
  /**
   * <code>uint64 instrumentid = 3;</code>
   */
  public long getInstrumentid() {
    return instrumentid_;
  }

  public static final int GENREID_FIELD_NUMBER = 4;
  private long genreid_;
  /**
   * <code>uint64 genreid = 4;</code>
   */
  public long getGenreid() {
    return genreid_;
  }

  public static final int DATETIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp dateTime_;
  /**
   * <code>.google.protobuf.Timestamp dateTime = 5;</code>
   */
  public boolean hasDateTime() {
    return dateTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dateTime = 5;</code>
   */
  public com.google.protobuf.Timestamp getDateTime() {
    return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp dateTime = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
    return getDateTime();
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 6;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 6;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (studentid_ != 0L) {
      output.writeUInt64(1, studentid_);
    }
    if (teacherid_ != 0L) {
      output.writeUInt64(2, teacherid_);
    }
    if (instrumentid_ != 0L) {
      output.writeUInt64(3, instrumentid_);
    }
    if (genreid_ != 0L) {
      output.writeUInt64(4, genreid_);
    }
    if (dateTime_ != null) {
      output.writeMessage(5, getDateTime());
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (studentid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, studentid_);
    }
    if (teacherid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, teacherid_);
    }
    if (instrumentid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, instrumentid_);
    }
    if (genreid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, genreid_);
    }
    if (dateTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDateTime());
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.musicmantra.classbooking.addnewrecord.postBookingReq)) {
      return super.equals(obj);
    }
    com.musicmantra.classbooking.addnewrecord.postBookingReq other = (com.musicmantra.classbooking.addnewrecord.postBookingReq) obj;

    boolean result = true;
    result = result && (getStudentid()
        == other.getStudentid());
    result = result && (getTeacherid()
        == other.getTeacherid());
    result = result && (getInstrumentid()
        == other.getInstrumentid());
    result = result && (getGenreid()
        == other.getGenreid());
    result = result && (hasDateTime() == other.hasDateTime());
    if (hasDateTime()) {
      result = result && getDateTime()
          .equals(other.getDateTime());
    }
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStudentid());
    hash = (37 * hash) + TEACHERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTeacherid());
    hash = (37 * hash) + INSTRUMENTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInstrumentid());
    hash = (37 * hash) + GENREID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGenreid());
    if (hasDateTime()) {
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDateTime().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.musicmantra.classbooking.addnewrecord.postBookingReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.musicmantra.classbooking.addnewrecord.postBookingReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *defining request message format
   * </pre>
   *
   * Protobuf type {@code postBookingReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:postBookingReq)
      com.musicmantra.classbooking.addnewrecord.postBookingReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.musicmantra.classbooking.addnewrecord.BookingMethods.internal_static_postBookingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.musicmantra.classbooking.addnewrecord.BookingMethods.internal_static_postBookingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.musicmantra.classbooking.addnewrecord.postBookingReq.class, com.musicmantra.classbooking.addnewrecord.postBookingReq.Builder.class);
    }

    // Construct using com.musicmantra.classbooking.addnewrecord.postBookingReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      studentid_ = 0L;

      teacherid_ = 0L;

      instrumentid_ = 0L;

      genreid_ = 0L;

      if (dateTimeBuilder_ == null) {
        dateTime_ = null;
      } else {
        dateTime_ = null;
        dateTimeBuilder_ = null;
      }
      status_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.musicmantra.classbooking.addnewrecord.BookingMethods.internal_static_postBookingReq_descriptor;
    }

    @java.lang.Override
    public com.musicmantra.classbooking.addnewrecord.postBookingReq getDefaultInstanceForType() {
      return com.musicmantra.classbooking.addnewrecord.postBookingReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.musicmantra.classbooking.addnewrecord.postBookingReq build() {
      com.musicmantra.classbooking.addnewrecord.postBookingReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.musicmantra.classbooking.addnewrecord.postBookingReq buildPartial() {
      com.musicmantra.classbooking.addnewrecord.postBookingReq result = new com.musicmantra.classbooking.addnewrecord.postBookingReq(this);
      result.studentid_ = studentid_;
      result.teacherid_ = teacherid_;
      result.instrumentid_ = instrumentid_;
      result.genreid_ = genreid_;
      if (dateTimeBuilder_ == null) {
        result.dateTime_ = dateTime_;
      } else {
        result.dateTime_ = dateTimeBuilder_.build();
      }
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.musicmantra.classbooking.addnewrecord.postBookingReq) {
        return mergeFrom((com.musicmantra.classbooking.addnewrecord.postBookingReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.musicmantra.classbooking.addnewrecord.postBookingReq other) {
      if (other == com.musicmantra.classbooking.addnewrecord.postBookingReq.getDefaultInstance()) return this;
      if (other.getStudentid() != 0L) {
        setStudentid(other.getStudentid());
      }
      if (other.getTeacherid() != 0L) {
        setTeacherid(other.getTeacherid());
      }
      if (other.getInstrumentid() != 0L) {
        setInstrumentid(other.getInstrumentid());
      }
      if (other.getGenreid() != 0L) {
        setGenreid(other.getGenreid());
      }
      if (other.hasDateTime()) {
        mergeDateTime(other.getDateTime());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.musicmantra.classbooking.addnewrecord.postBookingReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.musicmantra.classbooking.addnewrecord.postBookingReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long studentid_ ;
    /**
     * <code>uint64 studentid = 1;</code>
     */
    public long getStudentid() {
      return studentid_;
    }
    /**
     * <code>uint64 studentid = 1;</code>
     */
    public Builder setStudentid(long value) {
      
      studentid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 studentid = 1;</code>
     */
    public Builder clearStudentid() {
      
      studentid_ = 0L;
      onChanged();
      return this;
    }

    private long teacherid_ ;
    /**
     * <code>uint64 teacherid = 2;</code>
     */
    public long getTeacherid() {
      return teacherid_;
    }
    /**
     * <code>uint64 teacherid = 2;</code>
     */
    public Builder setTeacherid(long value) {
      
      teacherid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 teacherid = 2;</code>
     */
    public Builder clearTeacherid() {
      
      teacherid_ = 0L;
      onChanged();
      return this;
    }

    private long instrumentid_ ;
    /**
     * <code>uint64 instrumentid = 3;</code>
     */
    public long getInstrumentid() {
      return instrumentid_;
    }
    /**
     * <code>uint64 instrumentid = 3;</code>
     */
    public Builder setInstrumentid(long value) {
      
      instrumentid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 instrumentid = 3;</code>
     */
    public Builder clearInstrumentid() {
      
      instrumentid_ = 0L;
      onChanged();
      return this;
    }

    private long genreid_ ;
    /**
     * <code>uint64 genreid = 4;</code>
     */
    public long getGenreid() {
      return genreid_;
    }
    /**
     * <code>uint64 genreid = 4;</code>
     */
    public Builder setGenreid(long value) {
      
      genreid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 genreid = 4;</code>
     */
    public Builder clearGenreid() {
      
      genreid_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dateTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public boolean hasDateTime() {
      return dateTimeBuilder_ != null || dateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public com.google.protobuf.Timestamp getDateTime() {
      if (dateTimeBuilder_ == null) {
        return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
      } else {
        return dateTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public Builder setDateTime(com.google.protobuf.Timestamp value) {
      if (dateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateTime_ = value;
        onChanged();
      } else {
        dateTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public Builder setDateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateTimeBuilder_ == null) {
        dateTime_ = builderForValue.build();
        onChanged();
      } else {
        dateTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
      if (dateTimeBuilder_ == null) {
        if (dateTime_ != null) {
          dateTime_ =
            com.google.protobuf.Timestamp.newBuilder(dateTime_).mergeFrom(value).buildPartial();
        } else {
          dateTime_ = value;
        }
        onChanged();
      } else {
        dateTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public Builder clearDateTime() {
      if (dateTimeBuilder_ == null) {
        dateTime_ = null;
        onChanged();
      } else {
        dateTime_ = null;
        dateTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
      
      onChanged();
      return getDateTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      if (dateTimeBuilder_ != null) {
        return dateTimeBuilder_.getMessageOrBuilder();
      } else {
        return dateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateTimeFieldBuilder() {
      if (dateTimeBuilder_ == null) {
        dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateTime(),
                getParentForChildren(),
                isClean());
        dateTime_ = null;
      }
      return dateTimeBuilder_;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 6;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 6;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 6;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:postBookingReq)
  }

  // @@protoc_insertion_point(class_scope:postBookingReq)
  private static final com.musicmantra.classbooking.addnewrecord.postBookingReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.musicmantra.classbooking.addnewrecord.postBookingReq();
  }

  public static com.musicmantra.classbooking.addnewrecord.postBookingReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<postBookingReq>
      PARSER = new com.google.protobuf.AbstractParser<postBookingReq>() {
    @java.lang.Override
    public postBookingReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new postBookingReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<postBookingReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<postBookingReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.musicmantra.classbooking.addnewrecord.postBookingReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

