// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.addnewrecord;

public interface postBookingReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:postBookingReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 studentid = 1;</code>
   */
  long getStudentid();

  /**
   * <code>uint64 teacherid = 2;</code>
   */
  long getTeacherid();

  /**
   * <code>uint64 instrumentid = 3;</code>
   */
  long getInstrumentid();

  /**
   * <code>uint64 genreid = 4;</code>
   */
  long getGenreid();

  /**
   * <code>.google.protobuf.Timestamp dateTime = 5;</code>
   */
  boolean hasDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 5;</code>
   */
  com.google.protobuf.Timestamp getDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

  /**
   * <code>string status = 6;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
