// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.stackroute.musicmantra.booking;

public final class BookingMethodsOuterClass {
  private BookingMethodsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface getBookingReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getBookingReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 studentid = 1;</code>
     */
    long getStudentid();

    /**
     * <code>uint64 sessionid = 2;</code>
     */
    long getSessionid();
  }
  /**
   * Protobuf type {@code getBookingReq}
   */
  public  static final class getBookingReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:getBookingReq)
      getBookingReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getBookingReq.newBuilder() to construct.
    private getBookingReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getBookingReq() {
      studentid_ = 0L;
      sessionid_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getBookingReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              studentid_ = input.readUInt64();
              break;
            }
            case 16: {

              sessionid_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.class, com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.Builder.class);
    }

    public static final int STUDENTID_FIELD_NUMBER = 1;
    private long studentid_;
    /**
     * <code>uint64 studentid = 1;</code>
     */
    public long getStudentid() {
      return studentid_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private long sessionid_;
    /**
     * <code>uint64 sessionid = 2;</code>
     */
    public long getSessionid() {
      return sessionid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (studentid_ != 0L) {
        output.writeUInt64(1, studentid_);
      }
      if (sessionid_ != 0L) {
        output.writeUInt64(2, sessionid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (studentid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, studentid_);
      }
      if (sessionid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, sessionid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq)) {
        return super.equals(obj);
      }
      com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq other = (com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq) obj;

      boolean result = true;
      result = result && (getStudentid()
          == other.getStudentid());
      result = result && (getSessionid()
          == other.getSessionid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStudentid());
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getBookingReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getBookingReq)
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.class, com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.Builder.class);
      }

      // Construct using com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        studentid_ = 0L;

        sessionid_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingReq_descriptor;
      }

      @java.lang.Override
      public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq getDefaultInstanceForType() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq build() {
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq buildPartial() {
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq result = new com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq(this);
        result.studentid_ = studentid_;
        result.sessionid_ = sessionid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq) {
          return mergeFrom((com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq other) {
        if (other == com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq.getDefaultInstance()) return this;
        if (other.getStudentid() != 0L) {
          setStudentid(other.getStudentid());
        }
        if (other.getSessionid() != 0L) {
          setSessionid(other.getSessionid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long studentid_ ;
      /**
       * <code>uint64 studentid = 1;</code>
       */
      public long getStudentid() {
        return studentid_;
      }
      /**
       * <code>uint64 studentid = 1;</code>
       */
      public Builder setStudentid(long value) {
        
        studentid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 studentid = 1;</code>
       */
      public Builder clearStudentid() {
        
        studentid_ = 0L;
        onChanged();
        return this;
      }

      private long sessionid_ ;
      /**
       * <code>uint64 sessionid = 2;</code>
       */
      public long getSessionid() {
        return sessionid_;
      }
      /**
       * <code>uint64 sessionid = 2;</code>
       */
      public Builder setSessionid(long value) {
        
        sessionid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sessionid = 2;</code>
       */
      public Builder clearSessionid() {
        
        sessionid_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:getBookingReq)
    }

    // @@protoc_insertion_point(class_scope:getBookingReq)
    private static final com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq();
    }

    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getBookingReq>
        PARSER = new com.google.protobuf.AbstractParser<getBookingReq>() {
      @java.lang.Override
      public getBookingReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getBookingReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getBookingReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getBookingReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getBookingRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:getBookingResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 bookingid = 1;</code>
     */
    long getBookingid();

    /**
     * <code>uint64 studentid = 2;</code>
     */
    long getStudentid();

    /**
     * <code>uint64 sessionid = 3;</code>
     */
    long getSessionid();

    /**
     * <code>string status = 4;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
     */
    boolean hasBookingdatetime();
    /**
     * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
     */
    com.google.protobuf.Timestamp getBookingdatetime();
    /**
     * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBookingdatetimeOrBuilder();
  }
  /**
   * Protobuf type {@code getBookingResp}
   */
  public  static final class getBookingResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:getBookingResp)
      getBookingRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getBookingResp.newBuilder() to construct.
    private getBookingResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getBookingResp() {
      bookingid_ = 0L;
      studentid_ = 0L;
      sessionid_ = 0L;
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getBookingResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bookingid_ = input.readUInt64();
              break;
            }
            case 16: {

              studentid_ = input.readUInt64();
              break;
            }
            case 24: {

              sessionid_ = input.readUInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (bookingdatetime_ != null) {
                subBuilder = bookingdatetime_.toBuilder();
              }
              bookingdatetime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bookingdatetime_);
                bookingdatetime_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.class, com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.Builder.class);
    }

    public static final int BOOKINGID_FIELD_NUMBER = 1;
    private long bookingid_;
    /**
     * <code>uint64 bookingid = 1;</code>
     */
    public long getBookingid() {
      return bookingid_;
    }

    public static final int STUDENTID_FIELD_NUMBER = 2;
    private long studentid_;
    /**
     * <code>uint64 studentid = 2;</code>
     */
    public long getStudentid() {
      return studentid_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionid_;
    /**
     * <code>uint64 sessionid = 3;</code>
     */
    public long getSessionid() {
      return sessionid_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 4;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKINGDATETIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp bookingdatetime_;
    /**
     * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
     */
    public boolean hasBookingdatetime() {
      return bookingdatetime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
     */
    public com.google.protobuf.Timestamp getBookingdatetime() {
      return bookingdatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bookingdatetime_;
    }
    /**
     * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBookingdatetimeOrBuilder() {
      return getBookingdatetime();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookingid_ != 0L) {
        output.writeUInt64(1, bookingid_);
      }
      if (studentid_ != 0L) {
        output.writeUInt64(2, studentid_);
      }
      if (sessionid_ != 0L) {
        output.writeUInt64(3, sessionid_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
      }
      if (bookingdatetime_ != null) {
        output.writeMessage(5, getBookingdatetime());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookingid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, bookingid_);
      }
      if (studentid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, studentid_);
      }
      if (sessionid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, sessionid_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
      }
      if (bookingdatetime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getBookingdatetime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp)) {
        return super.equals(obj);
      }
      com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp other = (com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp) obj;

      boolean result = true;
      result = result && (getBookingid()
          == other.getBookingid());
      result = result && (getStudentid()
          == other.getStudentid());
      result = result && (getSessionid()
          == other.getSessionid());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && (hasBookingdatetime() == other.hasBookingdatetime());
      if (hasBookingdatetime()) {
        result = result && getBookingdatetime()
            .equals(other.getBookingdatetime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOKINGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBookingid());
      hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStudentid());
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionid());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      if (hasBookingdatetime()) {
        hash = (37 * hash) + BOOKINGDATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getBookingdatetime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getBookingResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:getBookingResp)
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.class, com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.Builder.class);
      }

      // Construct using com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bookingid_ = 0L;

        studentid_ = 0L;

        sessionid_ = 0L;

        status_ = "";

        if (bookingdatetimeBuilder_ == null) {
          bookingdatetime_ = null;
        } else {
          bookingdatetime_ = null;
          bookingdatetimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.internal_static_getBookingResp_descriptor;
      }

      @java.lang.Override
      public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp getDefaultInstanceForType() {
        return com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp build() {
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp buildPartial() {
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp result = new com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp(this);
        result.bookingid_ = bookingid_;
        result.studentid_ = studentid_;
        result.sessionid_ = sessionid_;
        result.status_ = status_;
        if (bookingdatetimeBuilder_ == null) {
          result.bookingdatetime_ = bookingdatetime_;
        } else {
          result.bookingdatetime_ = bookingdatetimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp) {
          return mergeFrom((com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp other) {
        if (other == com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp.getDefaultInstance()) return this;
        if (other.getBookingid() != 0L) {
          setBookingid(other.getBookingid());
        }
        if (other.getStudentid() != 0L) {
          setStudentid(other.getStudentid());
        }
        if (other.getSessionid() != 0L) {
          setSessionid(other.getSessionid());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (other.hasBookingdatetime()) {
          mergeBookingdatetime(other.getBookingdatetime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long bookingid_ ;
      /**
       * <code>uint64 bookingid = 1;</code>
       */
      public long getBookingid() {
        return bookingid_;
      }
      /**
       * <code>uint64 bookingid = 1;</code>
       */
      public Builder setBookingid(long value) {
        
        bookingid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 bookingid = 1;</code>
       */
      public Builder clearBookingid() {
        
        bookingid_ = 0L;
        onChanged();
        return this;
      }

      private long studentid_ ;
      /**
       * <code>uint64 studentid = 2;</code>
       */
      public long getStudentid() {
        return studentid_;
      }
      /**
       * <code>uint64 studentid = 2;</code>
       */
      public Builder setStudentid(long value) {
        
        studentid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 studentid = 2;</code>
       */
      public Builder clearStudentid() {
        
        studentid_ = 0L;
        onChanged();
        return this;
      }

      private long sessionid_ ;
      /**
       * <code>uint64 sessionid = 3;</code>
       */
      public long getSessionid() {
        return sessionid_;
      }
      /**
       * <code>uint64 sessionid = 3;</code>
       */
      public Builder setSessionid(long value) {
        
        sessionid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sessionid = 3;</code>
       */
      public Builder clearSessionid() {
        
        sessionid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 4;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp bookingdatetime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> bookingdatetimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public boolean hasBookingdatetime() {
        return bookingdatetimeBuilder_ != null || bookingdatetime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public com.google.protobuf.Timestamp getBookingdatetime() {
        if (bookingdatetimeBuilder_ == null) {
          return bookingdatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bookingdatetime_;
        } else {
          return bookingdatetimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public Builder setBookingdatetime(com.google.protobuf.Timestamp value) {
        if (bookingdatetimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bookingdatetime_ = value;
          onChanged();
        } else {
          bookingdatetimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public Builder setBookingdatetime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (bookingdatetimeBuilder_ == null) {
          bookingdatetime_ = builderForValue.build();
          onChanged();
        } else {
          bookingdatetimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public Builder mergeBookingdatetime(com.google.protobuf.Timestamp value) {
        if (bookingdatetimeBuilder_ == null) {
          if (bookingdatetime_ != null) {
            bookingdatetime_ =
              com.google.protobuf.Timestamp.newBuilder(bookingdatetime_).mergeFrom(value).buildPartial();
          } else {
            bookingdatetime_ = value;
          }
          onChanged();
        } else {
          bookingdatetimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public Builder clearBookingdatetime() {
        if (bookingdatetimeBuilder_ == null) {
          bookingdatetime_ = null;
          onChanged();
        } else {
          bookingdatetime_ = null;
          bookingdatetimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBookingdatetimeBuilder() {
        
        onChanged();
        return getBookingdatetimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBookingdatetimeOrBuilder() {
        if (bookingdatetimeBuilder_ != null) {
          return bookingdatetimeBuilder_.getMessageOrBuilder();
        } else {
          return bookingdatetime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : bookingdatetime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp bookingdatetime = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBookingdatetimeFieldBuilder() {
        if (bookingdatetimeBuilder_ == null) {
          bookingdatetimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBookingdatetime(),
                  getParentForChildren(),
                  isClean());
          bookingdatetime_ = null;
        }
        return bookingdatetimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:getBookingResp)
    }

    // @@protoc_insertion_point(class_scope:getBookingResp)
    private static final com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp();
    }

    public static com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getBookingResp>
        PARSER = new com.google.protobuf.AbstractParser<getBookingResp>() {
      @java.lang.Override
      public getBookingResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getBookingResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getBookingResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getBookingResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stackroute.musicmantra.booking.BookingMethodsOuterClass.getBookingResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getBookingReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getBookingReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getBookingResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getBookingResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BookingMethods.proto\032\037google/protobuf/" +
      "timestamp.proto\"5\n\rgetBookingReq\022\021\n\tstud" +
      "entid\030\001 \001(\004\022\021\n\tsessionid\030\002 \001(\004\"\216\001\n\016getBo" +
      "okingResp\022\021\n\tbookingid\030\001 \001(\004\022\021\n\tstudenti" +
      "d\030\002 \001(\004\022\021\n\tsessionid\030\003 \001(\004\022\016\n\006status\030\004 \001" +
      "(\t\0223\n\017bookingdatetime\030\005 \001(\0132\032.google.pro" +
      "tobuf.Timestamp2?\n\016BookingMethods\022-\n\nget" +
      "Booking\022\016.getBookingReq\032\017.getBookingResp" +
      "B$\n\"com.stackroute.musicmantra.bookingb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_getBookingReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getBookingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getBookingReq_descriptor,
        new java.lang.String[] { "Studentid", "Sessionid", });
    internal_static_getBookingResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getBookingResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getBookingResp_descriptor,
        new java.lang.String[] { "Bookingid", "Studentid", "Sessionid", "Status", "Bookingdatetime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
