version: "2"
services:
  UserService:
    image: userimage
    container_name: user-service
    restart: on-failure
    network_mode: host
    build: ./user-service
    ports:
      - "8086:8086"
  RecommendationService:
    image: rcmdserviceimage
    container_name: recommendation-service
    restart: on-failure
    network_mode: host
    build: ./recommendation-service
    ports:
      - "8081:8081"
