// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.generatedfiles;

public interface deleteBookingReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteBookingReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 bookingid = 1;</code>
   */
  long getBookingid();
}
