// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.generatedfiles;

/**
 * <pre>
 *multi records response message
 * </pre>
 *
 * Protobuf type {@code multiBookingResp}
 */
public  final class multiBookingResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:multiBookingResp)
    multiBookingRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use multiBookingResp.newBuilder() to construct.
  private multiBookingResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private multiBookingResp() {
    bookinid_ = 0L;
    studentid_ = 0L;
    sessionid_ = 0L;
    lastupdate_ = "";
    bookingstatus_ = "";
    errormsg_ = "";
    statuscode_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private multiBookingResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            bookinid_ = input.readUInt64();
            break;
          }
          case 16: {

            studentid_ = input.readUInt64();
            break;
          }
          case 24: {

            sessionid_ = input.readUInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            lastupdate_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            bookingstatus_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            errormsg_ = s;
            break;
          }
          case 56: {

            statuscode_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.musicmantra.classbooking.generatedfiles.BookingMethods.internal_static_multiBookingResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.musicmantra.classbooking.generatedfiles.BookingMethods.internal_static_multiBookingResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.musicmantra.classbooking.generatedfiles.multiBookingResp.class, com.musicmantra.classbooking.generatedfiles.multiBookingResp.Builder.class);
  }

  public static final int BOOKINID_FIELD_NUMBER = 1;
  private long bookinid_;
  /**
   * <code>uint64 bookinid = 1;</code>
   */
  public long getBookinid() {
    return bookinid_;
  }

  public static final int STUDENTID_FIELD_NUMBER = 2;
  private long studentid_;
  /**
   * <code>uint64 studentid = 2;</code>
   */
  public long getStudentid() {
    return studentid_;
  }

  public static final int SESSIONID_FIELD_NUMBER = 3;
  private long sessionid_;
  /**
   * <code>uint64 sessionid = 3;</code>
   */
  public long getSessionid() {
    return sessionid_;
  }

  public static final int LASTUPDATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object lastupdate_;
  /**
   * <code>string lastupdate = 4;</code>
   */
  public java.lang.String getLastupdate() {
    java.lang.Object ref = lastupdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastupdate_ = s;
      return s;
    }
  }
  /**
   * <code>string lastupdate = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLastupdateBytes() {
    java.lang.Object ref = lastupdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastupdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOKINGSTATUS_FIELD_NUMBER = 5;
  private volatile java.lang.Object bookingstatus_;
  /**
   * <code>string bookingstatus = 5;</code>
   */
  public java.lang.String getBookingstatus() {
    java.lang.Object ref = bookingstatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bookingstatus_ = s;
      return s;
    }
  }
  /**
   * <code>string bookingstatus = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBookingstatusBytes() {
    java.lang.Object ref = bookingstatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookingstatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORMSG_FIELD_NUMBER = 6;
  private volatile java.lang.Object errormsg_;
  /**
   * <code>string errormsg = 6;</code>
   */
  public java.lang.String getErrormsg() {
    java.lang.Object ref = errormsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errormsg_ = s;
      return s;
    }
  }
  /**
   * <code>string errormsg = 6;</code>
   */
  public com.google.protobuf.ByteString
      getErrormsgBytes() {
    java.lang.Object ref = errormsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errormsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUSCODE_FIELD_NUMBER = 7;
  private int statuscode_;
  /**
   * <code>int32 statuscode = 7;</code>
   */
  public int getStatuscode() {
    return statuscode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bookinid_ != 0L) {
      output.writeUInt64(1, bookinid_);
    }
    if (studentid_ != 0L) {
      output.writeUInt64(2, studentid_);
    }
    if (sessionid_ != 0L) {
      output.writeUInt64(3, sessionid_);
    }
    if (!getLastupdateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastupdate_);
    }
    if (!getBookingstatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, bookingstatus_);
    }
    if (!getErrormsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errormsg_);
    }
    if (statuscode_ != 0) {
      output.writeInt32(7, statuscode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bookinid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, bookinid_);
    }
    if (studentid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, studentid_);
    }
    if (sessionid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, sessionid_);
    }
    if (!getLastupdateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastupdate_);
    }
    if (!getBookingstatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, bookingstatus_);
    }
    if (!getErrormsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errormsg_);
    }
    if (statuscode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, statuscode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.musicmantra.classbooking.generatedfiles.multiBookingResp)) {
      return super.equals(obj);
    }
    com.musicmantra.classbooking.generatedfiles.multiBookingResp other = (com.musicmantra.classbooking.generatedfiles.multiBookingResp) obj;

    boolean result = true;
    result = result && (getBookinid()
        == other.getBookinid());
    result = result && (getStudentid()
        == other.getStudentid());
    result = result && (getSessionid()
        == other.getSessionid());
    result = result && getLastupdate()
        .equals(other.getLastupdate());
    result = result && getBookingstatus()
        .equals(other.getBookingstatus());
    result = result && getErrormsg()
        .equals(other.getErrormsg());
    result = result && (getStatuscode()
        == other.getStatuscode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKINID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBookinid());
    hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStudentid());
    hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionid());
    hash = (37 * hash) + LASTUPDATE_FIELD_NUMBER;
    hash = (53 * hash) + getLastupdate().hashCode();
    hash = (37 * hash) + BOOKINGSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getBookingstatus().hashCode();
    hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrormsg().hashCode();
    hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
    hash = (53 * hash) + getStatuscode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.musicmantra.classbooking.generatedfiles.multiBookingResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *multi records response message
   * </pre>
   *
   * Protobuf type {@code multiBookingResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:multiBookingResp)
      com.musicmantra.classbooking.generatedfiles.multiBookingRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.musicmantra.classbooking.generatedfiles.BookingMethods.internal_static_multiBookingResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.musicmantra.classbooking.generatedfiles.BookingMethods.internal_static_multiBookingResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.musicmantra.classbooking.generatedfiles.multiBookingResp.class, com.musicmantra.classbooking.generatedfiles.multiBookingResp.Builder.class);
    }

    // Construct using com.musicmantra.classbooking.generatedfiles.multiBookingResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bookinid_ = 0L;

      studentid_ = 0L;

      sessionid_ = 0L;

      lastupdate_ = "";

      bookingstatus_ = "";

      errormsg_ = "";

      statuscode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.musicmantra.classbooking.generatedfiles.BookingMethods.internal_static_multiBookingResp_descriptor;
    }

    @java.lang.Override
    public com.musicmantra.classbooking.generatedfiles.multiBookingResp getDefaultInstanceForType() {
      return com.musicmantra.classbooking.generatedfiles.multiBookingResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.musicmantra.classbooking.generatedfiles.multiBookingResp build() {
      com.musicmantra.classbooking.generatedfiles.multiBookingResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.musicmantra.classbooking.generatedfiles.multiBookingResp buildPartial() {
      com.musicmantra.classbooking.generatedfiles.multiBookingResp result = new com.musicmantra.classbooking.generatedfiles.multiBookingResp(this);
      result.bookinid_ = bookinid_;
      result.studentid_ = studentid_;
      result.sessionid_ = sessionid_;
      result.lastupdate_ = lastupdate_;
      result.bookingstatus_ = bookingstatus_;
      result.errormsg_ = errormsg_;
      result.statuscode_ = statuscode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.musicmantra.classbooking.generatedfiles.multiBookingResp) {
        return mergeFrom((com.musicmantra.classbooking.generatedfiles.multiBookingResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.musicmantra.classbooking.generatedfiles.multiBookingResp other) {
      if (other == com.musicmantra.classbooking.generatedfiles.multiBookingResp.getDefaultInstance()) return this;
      if (other.getBookinid() != 0L) {
        setBookinid(other.getBookinid());
      }
      if (other.getStudentid() != 0L) {
        setStudentid(other.getStudentid());
      }
      if (other.getSessionid() != 0L) {
        setSessionid(other.getSessionid());
      }
      if (!other.getLastupdate().isEmpty()) {
        lastupdate_ = other.lastupdate_;
        onChanged();
      }
      if (!other.getBookingstatus().isEmpty()) {
        bookingstatus_ = other.bookingstatus_;
        onChanged();
      }
      if (!other.getErrormsg().isEmpty()) {
        errormsg_ = other.errormsg_;
        onChanged();
      }
      if (other.getStatuscode() != 0) {
        setStatuscode(other.getStatuscode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.musicmantra.classbooking.generatedfiles.multiBookingResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.musicmantra.classbooking.generatedfiles.multiBookingResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long bookinid_ ;
    /**
     * <code>uint64 bookinid = 1;</code>
     */
    public long getBookinid() {
      return bookinid_;
    }
    /**
     * <code>uint64 bookinid = 1;</code>
     */
    public Builder setBookinid(long value) {
      
      bookinid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 bookinid = 1;</code>
     */
    public Builder clearBookinid() {
      
      bookinid_ = 0L;
      onChanged();
      return this;
    }

    private long studentid_ ;
    /**
     * <code>uint64 studentid = 2;</code>
     */
    public long getStudentid() {
      return studentid_;
    }
    /**
     * <code>uint64 studentid = 2;</code>
     */
    public Builder setStudentid(long value) {
      
      studentid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 studentid = 2;</code>
     */
    public Builder clearStudentid() {
      
      studentid_ = 0L;
      onChanged();
      return this;
    }

    private long sessionid_ ;
    /**
     * <code>uint64 sessionid = 3;</code>
     */
    public long getSessionid() {
      return sessionid_;
    }
    /**
     * <code>uint64 sessionid = 3;</code>
     */
    public Builder setSessionid(long value) {
      
      sessionid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 sessionid = 3;</code>
     */
    public Builder clearSessionid() {
      
      sessionid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object lastupdate_ = "";
    /**
     * <code>string lastupdate = 4;</code>
     */
    public java.lang.String getLastupdate() {
      java.lang.Object ref = lastupdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastupdate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastupdate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLastupdateBytes() {
      java.lang.Object ref = lastupdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastupdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastupdate = 4;</code>
     */
    public Builder setLastupdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastupdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastupdate = 4;</code>
     */
    public Builder clearLastupdate() {
      
      lastupdate_ = getDefaultInstance().getLastupdate();
      onChanged();
      return this;
    }
    /**
     * <code>string lastupdate = 4;</code>
     */
    public Builder setLastupdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastupdate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bookingstatus_ = "";
    /**
     * <code>string bookingstatus = 5;</code>
     */
    public java.lang.String getBookingstatus() {
      java.lang.Object ref = bookingstatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookingstatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bookingstatus = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBookingstatusBytes() {
      java.lang.Object ref = bookingstatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingstatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bookingstatus = 5;</code>
     */
    public Builder setBookingstatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bookingstatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bookingstatus = 5;</code>
     */
    public Builder clearBookingstatus() {
      
      bookingstatus_ = getDefaultInstance().getBookingstatus();
      onChanged();
      return this;
    }
    /**
     * <code>string bookingstatus = 5;</code>
     */
    public Builder setBookingstatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bookingstatus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errormsg_ = "";
    /**
     * <code>string errormsg = 6;</code>
     */
    public java.lang.String getErrormsg() {
      java.lang.Object ref = errormsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errormsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errormsg = 6;</code>
     */
    public com.google.protobuf.ByteString
        getErrormsgBytes() {
      java.lang.Object ref = errormsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errormsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errormsg = 6;</code>
     */
    public Builder setErrormsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errormsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errormsg = 6;</code>
     */
    public Builder clearErrormsg() {
      
      errormsg_ = getDefaultInstance().getErrormsg();
      onChanged();
      return this;
    }
    /**
     * <code>string errormsg = 6;</code>
     */
    public Builder setErrormsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errormsg_ = value;
      onChanged();
      return this;
    }

    private int statuscode_ ;
    /**
     * <code>int32 statuscode = 7;</code>
     */
    public int getStatuscode() {
      return statuscode_;
    }
    /**
     * <code>int32 statuscode = 7;</code>
     */
    public Builder setStatuscode(int value) {
      
      statuscode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 statuscode = 7;</code>
     */
    public Builder clearStatuscode() {
      
      statuscode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:multiBookingResp)
  }

  // @@protoc_insertion_point(class_scope:multiBookingResp)
  private static final com.musicmantra.classbooking.generatedfiles.multiBookingResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.musicmantra.classbooking.generatedfiles.multiBookingResp();
  }

  public static com.musicmantra.classbooking.generatedfiles.multiBookingResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<multiBookingResp>
      PARSER = new com.google.protobuf.AbstractParser<multiBookingResp>() {
    @java.lang.Override
    public multiBookingResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new multiBookingResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<multiBookingResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<multiBookingResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.musicmantra.classbooking.generatedfiles.multiBookingResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

