// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.generatedfiles;

public interface studentRecordsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:studentRecordsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 studentid = 1;</code>
   */
  long getStudentid();
}
