// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingMethods.proto

package com.musicmantra.classbooking.generatedfiles;

public interface updatereqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updatereq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 bookingid = 1;</code>
   */
  long getBookingid();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
