// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Update_profile.proto

package com.stackroute.musicmantra.noty5.emailserver.update_profile;

public interface updateProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updateProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 Responsecode = 2;</code>
   */
  int getResponsecode();
}
