FROM openjdk:11
EXPOSE 8084
ADD /target/feedback-and-review-service-1.0-SNAPSHOT-jar-with-dependencies.jar feedback-and-review-service-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar","feedback-and-review-service-1.0-SNAPSHOT-jar-with-dependencies.jar"]