// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendteacher.proto

package com.musicmantra.recommendationservice.grpc;

public final class Recommendteacher {
  private Recommendteacher() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface recommendationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recommendationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 studentId = 1;</code>
     */
    int getStudentId();
  }
  /**
   * Protobuf type {@code recommendationRequest}
   */
  public  static final class recommendationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:recommendationRequest)
      recommendationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use recommendationRequest.newBuilder() to construct.
    private recommendationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private recommendationRequest() {
      studentId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private recommendationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              studentId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.class, com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.Builder.class);
    }

    public static final int STUDENTID_FIELD_NUMBER = 1;
    private int studentId_;
    /**
     * <code>int32 studentId = 1;</code>
     */
    public int getStudentId() {
      return studentId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (studentId_ != 0) {
        output.writeInt32(1, studentId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (studentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, studentId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest)) {
        return super.equals(obj);
      }
      com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest other = (com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest) obj;

      boolean result = true;
      result = result && (getStudentId()
          == other.getStudentId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
      hash = (53 * hash) + getStudentId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recommendationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recommendationRequest)
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.class, com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.Builder.class);
      }

      // Construct using com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        studentId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationRequest_descriptor;
      }

      @java.lang.Override
      public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest getDefaultInstanceForType() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest build() {
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest buildPartial() {
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest result = new com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest(this);
        result.studentId_ = studentId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest) {
          return mergeFrom((com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest other) {
        if (other == com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest.getDefaultInstance()) return this;
        if (other.getStudentId() != 0) {
          setStudentId(other.getStudentId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int studentId_ ;
      /**
       * <code>int32 studentId = 1;</code>
       */
      public int getStudentId() {
        return studentId_;
      }
      /**
       * <code>int32 studentId = 1;</code>
       */
      public Builder setStudentId(int value) {
        
        studentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 studentId = 1;</code>
       */
      public Builder clearStudentId() {
        
        studentId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:recommendationRequest)
    }

    // @@protoc_insertion_point(class_scope:recommendationRequest)
    private static final com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest();
    }

    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<recommendationRequest>
        PARSER = new com.google.protobuf.AbstractParser<recommendationRequest>() {
      @java.lang.Override
      public recommendationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new recommendationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<recommendationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<recommendationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface recommendationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recommendationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     */
    int getResponseCode();

    /**
     * <code>string responseMessage = 2;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>int32 teacherId = 3;</code>
     */
    int getTeacherId();

    /**
     * <code>repeated string genre = 4;</code>
     */
    java.util.List<java.lang.String>
        getGenreList();
    /**
     * <code>repeated string genre = 4;</code>
     */
    int getGenreCount();
    /**
     * <code>repeated string genre = 4;</code>
     */
    java.lang.String getGenre(int index);
    /**
     * <code>repeated string genre = 4;</code>
     */
    com.google.protobuf.ByteString
        getGenreBytes(int index);

    /**
     * <code>repeated string instrument = 5;</code>
     */
    java.util.List<java.lang.String>
        getInstrumentList();
    /**
     * <code>repeated string instrument = 5;</code>
     */
    int getInstrumentCount();
    /**
     * <code>repeated string instrument = 5;</code>
     */
    java.lang.String getInstrument(int index);
    /**
     * <code>repeated string instrument = 5;</code>
     */
    com.google.protobuf.ByteString
        getInstrumentBytes(int index);
  }
  /**
   * Protobuf type {@code recommendationResponse}
   */
  public  static final class recommendationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:recommendationResponse)
      recommendationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use recommendationResponse.newBuilder() to construct.
    private recommendationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private recommendationResponse() {
      responseCode_ = 0;
      responseMessage_ = "";
      teacherId_ = 0;
      genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      instrument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private recommendationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responseCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 24: {

              teacherId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                genre_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              genre_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                instrument_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              instrument_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          genre_ = genre_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          instrument_ = instrument_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.class, com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 2;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEACHERID_FIELD_NUMBER = 3;
    private int teacherId_;
    /**
     * <code>int32 teacherId = 3;</code>
     */
    public int getTeacherId() {
      return teacherId_;
    }

    public static final int GENRE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList genre_;
    /**
     * <code>repeated string genre = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getGenreList() {
      return genre_;
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public int getGenreCount() {
      return genre_.size();
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public java.lang.String getGenre(int index) {
      return genre_.get(index);
    }
    /**
     * <code>repeated string genre = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGenreBytes(int index) {
      return genre_.getByteString(index);
    }

    public static final int INSTRUMENT_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList instrument_;
    /**
     * <code>repeated string instrument = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInstrumentList() {
      return instrument_;
    }
    /**
     * <code>repeated string instrument = 5;</code>
     */
    public int getInstrumentCount() {
      return instrument_.size();
    }
    /**
     * <code>repeated string instrument = 5;</code>
     */
    public java.lang.String getInstrument(int index) {
      return instrument_.get(index);
    }
    /**
     * <code>repeated string instrument = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes(int index) {
      return instrument_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCode_ != 0) {
        output.writeInt32(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMessage_);
      }
      if (teacherId_ != 0) {
        output.writeInt32(3, teacherId_);
      }
      for (int i = 0; i < genre_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, genre_.getRaw(i));
      }
      for (int i = 0; i < instrument_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, instrument_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMessage_);
      }
      if (teacherId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, teacherId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < genre_.size(); i++) {
          dataSize += computeStringSizeNoTag(genre_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGenreList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < instrument_.size(); i++) {
          dataSize += computeStringSizeNoTag(instrument_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInstrumentList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse)) {
        return super.equals(obj);
      }
      com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse other = (com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse) obj;

      boolean result = true;
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && (getTeacherId()
          == other.getTeacherId());
      result = result && getGenreList()
          .equals(other.getGenreList());
      result = result && getInstrumentList()
          .equals(other.getInstrumentList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (37 * hash) + TEACHERID_FIELD_NUMBER;
      hash = (53 * hash) + getTeacherId();
      if (getGenreCount() > 0) {
        hash = (37 * hash) + GENRE_FIELD_NUMBER;
        hash = (53 * hash) + getGenreList().hashCode();
      }
      if (getInstrumentCount() > 0) {
        hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
        hash = (53 * hash) + getInstrumentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recommendationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recommendationResponse)
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.class, com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.Builder.class);
      }

      // Construct using com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseCode_ = 0;

        responseMessage_ = "";

        teacherId_ = 0;

        genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        instrument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.internal_static_recommendationResponse_descriptor;
      }

      @java.lang.Override
      public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse getDefaultInstanceForType() {
        return com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse build() {
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse buildPartial() {
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse result = new com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.responseCode_ = responseCode_;
        result.responseMessage_ = responseMessage_;
        result.teacherId_ = teacherId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          genre_ = genre_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.genre_ = genre_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          instrument_ = instrument_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.instrument_ = instrument_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse) {
          return mergeFrom((com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse other) {
        if (other == com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse.getDefaultInstance()) return this;
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (other.getTeacherId() != 0) {
          setTeacherId(other.getTeacherId());
        }
        if (!other.genre_.isEmpty()) {
          if (genre_.isEmpty()) {
            genre_ = other.genre_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGenreIsMutable();
            genre_.addAll(other.genre_);
          }
          onChanged();
        }
        if (!other.instrument_.isEmpty()) {
          if (instrument_.isEmpty()) {
            instrument_ = other.instrument_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureInstrumentIsMutable();
            instrument_.addAll(other.instrument_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 2;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 2;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private int teacherId_ ;
      /**
       * <code>int32 teacherId = 3;</code>
       */
      public int getTeacherId() {
        return teacherId_;
      }
      /**
       * <code>int32 teacherId = 3;</code>
       */
      public Builder setTeacherId(int value) {
        
        teacherId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 teacherId = 3;</code>
       */
      public Builder clearTeacherId() {
        
        teacherId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGenreIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          genre_ = new com.google.protobuf.LazyStringArrayList(genre_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getGenreList() {
        return genre_.getUnmodifiableView();
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public int getGenreCount() {
        return genre_.size();
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public java.lang.String getGenre(int index) {
        return genre_.get(index);
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGenreBytes(int index) {
        return genre_.getByteString(index);
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public Builder setGenre(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
        genre_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public Builder addGenre(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
        genre_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public Builder addAllGenre(
          java.lang.Iterable<java.lang.String> values) {
        ensureGenreIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, genre_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public Builder clearGenre() {
        genre_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string genre = 4;</code>
       */
      public Builder addGenreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureGenreIsMutable();
        genre_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList instrument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInstrumentIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          instrument_ = new com.google.protobuf.LazyStringArrayList(instrument_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInstrumentList() {
        return instrument_.getUnmodifiableView();
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public int getInstrumentCount() {
        return instrument_.size();
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public java.lang.String getInstrument(int index) {
        return instrument_.get(index);
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInstrumentBytes(int index) {
        return instrument_.getByteString(index);
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public Builder setInstrument(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInstrumentIsMutable();
        instrument_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public Builder addInstrument(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInstrumentIsMutable();
        instrument_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public Builder addAllInstrument(
          java.lang.Iterable<java.lang.String> values) {
        ensureInstrumentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instrument_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public Builder clearInstrument() {
        instrument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instrument = 5;</code>
       */
      public Builder addInstrumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInstrumentIsMutable();
        instrument_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:recommendationResponse)
    }

    // @@protoc_insertion_point(class_scope:recommendationResponse)
    private static final com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse();
    }

    public static com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<recommendationResponse>
        PARSER = new com.google.protobuf.AbstractParser<recommendationResponse>() {
      @java.lang.Override
      public recommendationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new recommendationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<recommendationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<recommendationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.musicmantra.recommendationservice.grpc.Recommendteacher.recommendationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommendationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommendationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommendationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommendationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026recommendteacher.proto\"*\n\025recommendati" +
      "onRequest\022\021\n\tstudentId\030\001 \001(\005\"}\n\026recommen" +
      "dationResponse\022\024\n\014responseCode\030\001 \001(\005\022\027\n\017" +
      "responseMessage\030\002 \001(\t\022\021\n\tteacherId\030\003 \001(\005" +
      "\022\r\n\005genre\030\004 \003(\t\022\022\n\ninstrument\030\005 \003(\t2^\n\020R" +
      "ecommendTeacher\022J\n\025getRecommendedTeacher" +
      "\022\026.recommendationRequest\032\027.recommendatio" +
      "nResponse0\001B,\n*com.musicmantra.recommend" +
      "ationservice.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_recommendationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recommendationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommendationRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_recommendationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recommendationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommendationResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "ResponseMessage", "TeacherId", "Genre", "Instrument", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
