// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.stackroute;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeedbackReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FeedbackReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 FeedbackId = 1;</code>
     */
    int getFeedbackId();

    /**
     * <code>int32 BookingId = 2;</code>
     */
    int getBookingId();

    /**
     * <code>int32 FeedbackRating = 3;</code>
     */
    int getFeedbackRating();

    /**
     * <code>string Message = 4;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string Message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code FeedbackReq}
   */
  public  static final class FeedbackReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FeedbackReq)
      FeedbackReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeedbackReq.newBuilder() to construct.
    private FeedbackReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeedbackReq() {
      feedbackId_ = 0;
      bookingId_ = 0;
      feedbackRating_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              feedbackId_ = input.readInt32();
              break;
            }
            case 16: {

              bookingId_ = input.readInt32();
              break;
            }
            case 24: {

              feedbackRating_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stackroute.User.internal_static_FeedbackReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stackroute.User.internal_static_FeedbackReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stackroute.User.FeedbackReq.class, com.stackroute.User.FeedbackReq.Builder.class);
    }

    public static final int FEEDBACKID_FIELD_NUMBER = 1;
    private int feedbackId_;
    /**
     * <code>int32 FeedbackId = 1;</code>
     */
    public int getFeedbackId() {
      return feedbackId_;
    }

    public static final int BOOKINGID_FIELD_NUMBER = 2;
    private int bookingId_;
    /**
     * <code>int32 BookingId = 2;</code>
     */
    public int getBookingId() {
      return bookingId_;
    }

    public static final int FEEDBACKRATING_FIELD_NUMBER = 3;
    private int feedbackRating_;
    /**
     * <code>int32 FeedbackRating = 3;</code>
     */
    public int getFeedbackRating() {
      return feedbackRating_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object message_;
    /**
     * <code>string Message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string Message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (feedbackId_ != 0) {
        output.writeInt32(1, feedbackId_);
      }
      if (bookingId_ != 0) {
        output.writeInt32(2, bookingId_);
      }
      if (feedbackRating_ != 0) {
        output.writeInt32(3, feedbackRating_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (feedbackId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, feedbackId_);
      }
      if (bookingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bookingId_);
      }
      if (feedbackRating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, feedbackRating_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stackroute.User.FeedbackReq)) {
        return super.equals(obj);
      }
      com.stackroute.User.FeedbackReq other = (com.stackroute.User.FeedbackReq) obj;

      boolean result = true;
      result = result && (getFeedbackId()
          == other.getFeedbackId());
      result = result && (getBookingId()
          == other.getBookingId());
      result = result && (getFeedbackRating()
          == other.getFeedbackRating());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FEEDBACKID_FIELD_NUMBER;
      hash = (53 * hash) + getFeedbackId();
      hash = (37 * hash) + BOOKINGID_FIELD_NUMBER;
      hash = (53 * hash) + getBookingId();
      hash = (37 * hash) + FEEDBACKRATING_FIELD_NUMBER;
      hash = (53 * hash) + getFeedbackRating();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stackroute.User.FeedbackReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stackroute.User.FeedbackReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.FeedbackReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stackroute.User.FeedbackReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeedbackReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FeedbackReq)
        com.stackroute.User.FeedbackReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stackroute.User.internal_static_FeedbackReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stackroute.User.internal_static_FeedbackReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stackroute.User.FeedbackReq.class, com.stackroute.User.FeedbackReq.Builder.class);
      }

      // Construct using com.stackroute.User.FeedbackReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        feedbackId_ = 0;

        bookingId_ = 0;

        feedbackRating_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stackroute.User.internal_static_FeedbackReq_descriptor;
      }

      @java.lang.Override
      public com.stackroute.User.FeedbackReq getDefaultInstanceForType() {
        return com.stackroute.User.FeedbackReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.stackroute.User.FeedbackReq build() {
        com.stackroute.User.FeedbackReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stackroute.User.FeedbackReq buildPartial() {
        com.stackroute.User.FeedbackReq result = new com.stackroute.User.FeedbackReq(this);
        result.feedbackId_ = feedbackId_;
        result.bookingId_ = bookingId_;
        result.feedbackRating_ = feedbackRating_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stackroute.User.FeedbackReq) {
          return mergeFrom((com.stackroute.User.FeedbackReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stackroute.User.FeedbackReq other) {
        if (other == com.stackroute.User.FeedbackReq.getDefaultInstance()) return this;
        if (other.getFeedbackId() != 0) {
          setFeedbackId(other.getFeedbackId());
        }
        if (other.getBookingId() != 0) {
          setBookingId(other.getBookingId());
        }
        if (other.getFeedbackRating() != 0) {
          setFeedbackRating(other.getFeedbackRating());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stackroute.User.FeedbackReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stackroute.User.FeedbackReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int feedbackId_ ;
      /**
       * <code>int32 FeedbackId = 1;</code>
       */
      public int getFeedbackId() {
        return feedbackId_;
      }
      /**
       * <code>int32 FeedbackId = 1;</code>
       */
      public Builder setFeedbackId(int value) {
        
        feedbackId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 FeedbackId = 1;</code>
       */
      public Builder clearFeedbackId() {
        
        feedbackId_ = 0;
        onChanged();
        return this;
      }

      private int bookingId_ ;
      /**
       * <code>int32 BookingId = 2;</code>
       */
      public int getBookingId() {
        return bookingId_;
      }
      /**
       * <code>int32 BookingId = 2;</code>
       */
      public Builder setBookingId(int value) {
        
        bookingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 BookingId = 2;</code>
       */
      public Builder clearBookingId() {
        
        bookingId_ = 0;
        onChanged();
        return this;
      }

      private int feedbackRating_ ;
      /**
       * <code>int32 FeedbackRating = 3;</code>
       */
      public int getFeedbackRating() {
        return feedbackRating_;
      }
      /**
       * <code>int32 FeedbackRating = 3;</code>
       */
      public Builder setFeedbackRating(int value) {
        
        feedbackRating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 FeedbackRating = 3;</code>
       */
      public Builder clearFeedbackRating() {
        
        feedbackRating_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string Message = 4;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Message = 4;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Message = 4;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string Message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FeedbackReq)
    }

    // @@protoc_insertion_point(class_scope:FeedbackReq)
    private static final com.stackroute.User.FeedbackReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stackroute.User.FeedbackReq();
    }

    public static com.stackroute.User.FeedbackReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeedbackReq>
        PARSER = new com.google.protobuf.AbstractParser<FeedbackReq>() {
      @java.lang.Override
      public FeedbackReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeedbackReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeedbackReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stackroute.User.FeedbackReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FeedbackRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FeedbackResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 responceCode = 1;</code>
     */
    int getResponceCode();

    /**
     * <code>string responceMessage = 2;</code>
     */
    java.lang.String getResponceMessage();
    /**
     * <code>string responceMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponceMessageBytes();
  }
  /**
   * Protobuf type {@code FeedbackResp}
   */
  public  static final class FeedbackResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FeedbackResp)
      FeedbackRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FeedbackResp.newBuilder() to construct.
    private FeedbackResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FeedbackResp() {
      responceCode_ = 0;
      responceMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FeedbackResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responceCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responceMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stackroute.User.internal_static_FeedbackResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stackroute.User.internal_static_FeedbackResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stackroute.User.FeedbackResp.class, com.stackroute.User.FeedbackResp.Builder.class);
    }

    public static final int RESPONCECODE_FIELD_NUMBER = 1;
    private int responceCode_;
    /**
     * <code>int32 responceCode = 1;</code>
     */
    public int getResponceCode() {
      return responceCode_;
    }

    public static final int RESPONCEMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responceMessage_;
    /**
     * <code>string responceMessage = 2;</code>
     */
    public java.lang.String getResponceMessage() {
      java.lang.Object ref = responceMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responceMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responceMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponceMessageBytes() {
      java.lang.Object ref = responceMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responceMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responceCode_ != 0) {
        output.writeInt32(1, responceCode_);
      }
      if (!getResponceMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responceMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responceCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responceCode_);
      }
      if (!getResponceMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responceMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stackroute.User.FeedbackResp)) {
        return super.equals(obj);
      }
      com.stackroute.User.FeedbackResp other = (com.stackroute.User.FeedbackResp) obj;

      boolean result = true;
      result = result && (getResponceCode()
          == other.getResponceCode());
      result = result && getResponceMessage()
          .equals(other.getResponceMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONCECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponceCode();
      hash = (37 * hash) + RESPONCEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponceMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stackroute.User.FeedbackResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stackroute.User.FeedbackResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.FeedbackResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stackroute.User.FeedbackResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeedbackResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FeedbackResp)
        com.stackroute.User.FeedbackRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stackroute.User.internal_static_FeedbackResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stackroute.User.internal_static_FeedbackResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stackroute.User.FeedbackResp.class, com.stackroute.User.FeedbackResp.Builder.class);
      }

      // Construct using com.stackroute.User.FeedbackResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responceCode_ = 0;

        responceMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stackroute.User.internal_static_FeedbackResp_descriptor;
      }

      @java.lang.Override
      public com.stackroute.User.FeedbackResp getDefaultInstanceForType() {
        return com.stackroute.User.FeedbackResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.stackroute.User.FeedbackResp build() {
        com.stackroute.User.FeedbackResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stackroute.User.FeedbackResp buildPartial() {
        com.stackroute.User.FeedbackResp result = new com.stackroute.User.FeedbackResp(this);
        result.responceCode_ = responceCode_;
        result.responceMessage_ = responceMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stackroute.User.FeedbackResp) {
          return mergeFrom((com.stackroute.User.FeedbackResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stackroute.User.FeedbackResp other) {
        if (other == com.stackroute.User.FeedbackResp.getDefaultInstance()) return this;
        if (other.getResponceCode() != 0) {
          setResponceCode(other.getResponceCode());
        }
        if (!other.getResponceMessage().isEmpty()) {
          responceMessage_ = other.responceMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stackroute.User.FeedbackResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stackroute.User.FeedbackResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responceCode_ ;
      /**
       * <code>int32 responceCode = 1;</code>
       */
      public int getResponceCode() {
        return responceCode_;
      }
      /**
       * <code>int32 responceCode = 1;</code>
       */
      public Builder setResponceCode(int value) {
        
        responceCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responceCode = 1;</code>
       */
      public Builder clearResponceCode() {
        
        responceCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responceMessage_ = "";
      /**
       * <code>string responceMessage = 2;</code>
       */
      public java.lang.String getResponceMessage() {
        java.lang.Object ref = responceMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responceMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponceMessageBytes() {
        java.lang.Object ref = responceMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responceMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public Builder setResponceMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responceMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public Builder clearResponceMessage() {
        
        responceMessage_ = getDefaultInstance().getResponceMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public Builder setResponceMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responceMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FeedbackResp)
    }

    // @@protoc_insertion_point(class_scope:FeedbackResp)
    private static final com.stackroute.User.FeedbackResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stackroute.User.FeedbackResp();
    }

    public static com.stackroute.User.FeedbackResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeedbackResp>
        PARSER = new com.google.protobuf.AbstractParser<FeedbackResp>() {
      @java.lang.Override
      public FeedbackResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedbackResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FeedbackResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeedbackResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stackroute.User.FeedbackResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SessionReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 SessionId = 1;</code>
     */
    int getSessionId();

    /**
     * <code>string Enddate = 2;</code>
     */
    java.lang.String getEnddate();
    /**
     * <code>string Enddate = 2;</code>
     */
    com.google.protobuf.ByteString
        getEnddateBytes();
  }
  /**
   * Protobuf type {@code SessionReq}
   */
  public  static final class SessionReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SessionReq)
      SessionReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SessionReq.newBuilder() to construct.
    private SessionReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SessionReq() {
      sessionId_ = 0;
      enddate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SessionReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sessionId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              enddate_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stackroute.User.internal_static_SessionReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stackroute.User.internal_static_SessionReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stackroute.User.SessionReq.class, com.stackroute.User.SessionReq.Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private int sessionId_;
    /**
     * <code>int32 SessionId = 1;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int ENDDATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object enddate_;
    /**
     * <code>string Enddate = 2;</code>
     */
    public java.lang.String getEnddate() {
      java.lang.Object ref = enddate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enddate_ = s;
        return s;
      }
    }
    /**
     * <code>string Enddate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEnddateBytes() {
      java.lang.Object ref = enddate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enddate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionId_ != 0) {
        output.writeInt32(1, sessionId_);
      }
      if (!getEnddateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, enddate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionId_);
      }
      if (!getEnddateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, enddate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stackroute.User.SessionReq)) {
        return super.equals(obj);
      }
      com.stackroute.User.SessionReq other = (com.stackroute.User.SessionReq) obj;

      boolean result = true;
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && getEnddate()
          .equals(other.getEnddate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId();
      hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEnddate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stackroute.User.SessionReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.SessionReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.SessionReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.SessionReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stackroute.User.SessionReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.SessionReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stackroute.User.SessionReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SessionReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionReq)
        com.stackroute.User.SessionReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stackroute.User.internal_static_SessionReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stackroute.User.internal_static_SessionReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stackroute.User.SessionReq.class, com.stackroute.User.SessionReq.Builder.class);
      }

      // Construct using com.stackroute.User.SessionReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0;

        enddate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stackroute.User.internal_static_SessionReq_descriptor;
      }

      @java.lang.Override
      public com.stackroute.User.SessionReq getDefaultInstanceForType() {
        return com.stackroute.User.SessionReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.stackroute.User.SessionReq build() {
        com.stackroute.User.SessionReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stackroute.User.SessionReq buildPartial() {
        com.stackroute.User.SessionReq result = new com.stackroute.User.SessionReq(this);
        result.sessionId_ = sessionId_;
        result.enddate_ = enddate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stackroute.User.SessionReq) {
          return mergeFrom((com.stackroute.User.SessionReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stackroute.User.SessionReq other) {
        if (other == com.stackroute.User.SessionReq.getDefaultInstance()) return this;
        if (other.getSessionId() != 0) {
          setSessionId(other.getSessionId());
        }
        if (!other.getEnddate().isEmpty()) {
          enddate_ = other.enddate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stackroute.User.SessionReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stackroute.User.SessionReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>int32 SessionId = 1;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int32 SessionId = 1;</code>
       */
      public Builder setSessionId(int value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 SessionId = 1;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object enddate_ = "";
      /**
       * <code>string Enddate = 2;</code>
       */
      public java.lang.String getEnddate() {
        java.lang.Object ref = enddate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          enddate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Enddate = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEnddateBytes() {
        java.lang.Object ref = enddate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enddate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Enddate = 2;</code>
       */
      public Builder setEnddate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        enddate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Enddate = 2;</code>
       */
      public Builder clearEnddate() {
        
        enddate_ = getDefaultInstance().getEnddate();
        onChanged();
        return this;
      }
      /**
       * <code>string Enddate = 2;</code>
       */
      public Builder setEnddateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        enddate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SessionReq)
    }

    // @@protoc_insertion_point(class_scope:SessionReq)
    private static final com.stackroute.User.SessionReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stackroute.User.SessionReq();
    }

    public static com.stackroute.User.SessionReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SessionReq>
        PARSER = new com.google.protobuf.AbstractParser<SessionReq>() {
      @java.lang.Override
      public SessionReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SessionReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SessionReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stackroute.User.SessionReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SessionRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 responceCode = 1;</code>
     */
    int getResponceCode();

    /**
     * <code>string responceMessage = 2;</code>
     */
    java.lang.String getResponceMessage();
    /**
     * <code>string responceMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponceMessageBytes();
  }
  /**
   * Protobuf type {@code SessionResp}
   */
  public  static final class SessionResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SessionResp)
      SessionRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SessionResp.newBuilder() to construct.
    private SessionResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SessionResp() {
      responceCode_ = 0;
      responceMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SessionResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              responceCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responceMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stackroute.User.internal_static_SessionResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stackroute.User.internal_static_SessionResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stackroute.User.SessionResp.class, com.stackroute.User.SessionResp.Builder.class);
    }

    public static final int RESPONCECODE_FIELD_NUMBER = 1;
    private int responceCode_;
    /**
     * <code>int32 responceCode = 1;</code>
     */
    public int getResponceCode() {
      return responceCode_;
    }

    public static final int RESPONCEMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responceMessage_;
    /**
     * <code>string responceMessage = 2;</code>
     */
    public java.lang.String getResponceMessage() {
      java.lang.Object ref = responceMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responceMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responceMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponceMessageBytes() {
      java.lang.Object ref = responceMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responceMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responceCode_ != 0) {
        output.writeInt32(1, responceCode_);
      }
      if (!getResponceMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responceMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responceCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responceCode_);
      }
      if (!getResponceMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responceMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stackroute.User.SessionResp)) {
        return super.equals(obj);
      }
      com.stackroute.User.SessionResp other = (com.stackroute.User.SessionResp) obj;

      boolean result = true;
      result = result && (getResponceCode()
          == other.getResponceCode());
      result = result && getResponceMessage()
          .equals(other.getResponceMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONCECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponceCode();
      hash = (37 * hash) + RESPONCEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponceMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stackroute.User.SessionResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.SessionResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stackroute.User.SessionResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.SessionResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stackroute.User.SessionResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stackroute.User.SessionResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stackroute.User.SessionResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SessionResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionResp)
        com.stackroute.User.SessionRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stackroute.User.internal_static_SessionResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stackroute.User.internal_static_SessionResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stackroute.User.SessionResp.class, com.stackroute.User.SessionResp.Builder.class);
      }

      // Construct using com.stackroute.User.SessionResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responceCode_ = 0;

        responceMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stackroute.User.internal_static_SessionResp_descriptor;
      }

      @java.lang.Override
      public com.stackroute.User.SessionResp getDefaultInstanceForType() {
        return com.stackroute.User.SessionResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.stackroute.User.SessionResp build() {
        com.stackroute.User.SessionResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stackroute.User.SessionResp buildPartial() {
        com.stackroute.User.SessionResp result = new com.stackroute.User.SessionResp(this);
        result.responceCode_ = responceCode_;
        result.responceMessage_ = responceMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stackroute.User.SessionResp) {
          return mergeFrom((com.stackroute.User.SessionResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stackroute.User.SessionResp other) {
        if (other == com.stackroute.User.SessionResp.getDefaultInstance()) return this;
        if (other.getResponceCode() != 0) {
          setResponceCode(other.getResponceCode());
        }
        if (!other.getResponceMessage().isEmpty()) {
          responceMessage_ = other.responceMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stackroute.User.SessionResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stackroute.User.SessionResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responceCode_ ;
      /**
       * <code>int32 responceCode = 1;</code>
       */
      public int getResponceCode() {
        return responceCode_;
      }
      /**
       * <code>int32 responceCode = 1;</code>
       */
      public Builder setResponceCode(int value) {
        
        responceCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responceCode = 1;</code>
       */
      public Builder clearResponceCode() {
        
        responceCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responceMessage_ = "";
      /**
       * <code>string responceMessage = 2;</code>
       */
      public java.lang.String getResponceMessage() {
        java.lang.Object ref = responceMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responceMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponceMessageBytes() {
        java.lang.Object ref = responceMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responceMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public Builder setResponceMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responceMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public Builder clearResponceMessage() {
        
        responceMessage_ = getDefaultInstance().getResponceMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responceMessage = 2;</code>
       */
      public Builder setResponceMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responceMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SessionResp)
    }

    // @@protoc_insertion_point(class_scope:SessionResp)
    private static final com.stackroute.User.SessionResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stackroute.User.SessionResp();
    }

    public static com.stackroute.User.SessionResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SessionResp>
        PARSER = new com.google.protobuf.AbstractParser<SessionResp>() {
      @java.lang.Override
      public SessionResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SessionResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SessionResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stackroute.User.SessionResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeedbackReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeedbackReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeedbackResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeedbackResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SessionReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SessionReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SessionResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SessionResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"]\n\013FeedbackReq\022\022\n\nFeedbackI" +
      "d\030\001 \001(\005\022\021\n\tBookingId\030\002 \001(\005\022\026\n\016FeedbackRa" +
      "ting\030\003 \001(\005\022\017\n\007Message\030\004 \001(\t\"=\n\014FeedbackR" +
      "esp\022\024\n\014responceCode\030\001 \001(\005\022\027\n\017responceMes" +
      "sage\030\002 \001(\t\"0\n\nSessionReq\022\021\n\tSessionId\030\001 " +
      "\001(\005\022\017\n\007Enddate\030\002 \001(\t\"<\n\013SessionResp\022\024\n\014r" +
      "esponceCode\030\001 \001(\005\022\027\n\017responceMessage\030\002 \001" +
      "(\t2`\n\017FeedbackService\022\'\n\010Feedback\022\014.Feed" +
      "backReq\032\r.FeedbackResp\022$\n\007Session\022\013.Sess" +
      "ionReq\032\014.SessionRespB\020\n\016com.stackrouteb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FeedbackReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FeedbackReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeedbackReq_descriptor,
        new java.lang.String[] { "FeedbackId", "BookingId", "FeedbackRating", "Message", });
    internal_static_FeedbackResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FeedbackResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeedbackResp_descriptor,
        new java.lang.String[] { "ResponceCode", "ResponceMessage", });
    internal_static_SessionReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SessionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SessionReq_descriptor,
        new java.lang.String[] { "SessionId", "Enddate", });
    internal_static_SessionResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SessionResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SessionResp_descriptor,
        new java.lang.String[] { "ResponceCode", "ResponceMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
