// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_forgotPassword.proto

package com.stackroute.musicmantra.noty5.emailserver.register;

public final class RegistrationForgotPassword {
  private RegistrationForgotPassword() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OTPapiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OTPapiResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!registration_forgotPassword.proto\"\036\n\013m" +
      "ailRequest\022\017\n\007emailid\030\001 \001(\t\"D\n\016OTPapiRes" +
      "ponse\022\017\n\007message\030\001 \001(\t\022\013\n\003OTP\030\002 \001(\005\022\024\n\014r" +
      "esponsecode\030\003 \001(\005\"9\n\020sentmailResponse\022\017\n" +
      "\007message\030\001 \001(\t\022\024\n\014Responsecode\030\002 \001(\0052\273\001\n" +
      "\027RegistrationEmailServer\0225\n\024sendResetPas" +
      "swordOTP\022\014.mailRequest\032\017.OTPapiResponse\022" +
      "4\n\023sendRegistrationOTP\022\014.mailRequest\032\017.O" +
      "TPapiResponse\0223\n\020sendregistedMail\022\014.mail" +
      "Request\032\021.sentmailResponseB9\n5com.stackr" +
      "oute.musicmantra.noty5.emailserver.regis" +
      "terP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mailRequest_descriptor,
        new java.lang.String[] { "Emailid", });
    internal_static_OTPapiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OTPapiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OTPapiResponse_descriptor,
        new java.lang.String[] { "Message", "OTP", "Responsecode", });
    internal_static_sentmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sentmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentmailResponse_descriptor,
        new java.lang.String[] { "Message", "Responsecode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
