// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_forgotPassword.proto

package com.stackroute.musicmantra.noty5.emailserver.register;

public final class RegistrationForgotPassword {
  private RegistrationForgotPassword() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterVerifyied_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterVerifyied_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mailRequesttoregister_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mailRequesttoregister_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mailRequestforExistingUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mailRequestforExistingUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apiResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!registration_forgotPassword.proto\"9\n\021R" +
      "egisterVerifyied\022\023\n\013OTPverified\030\001 \001(\010\022\017\n" +
      "\007emailid\030\002 \001(\t\"(\n\025mailRequesttoregister\022" +
      "\017\n\007emailid\030\001 \001(\t\"J\n\032mailRequestforExisti" +
      "ngUser\022\017\n\007emailid\030\001 \001(\t\022\033\n\010mailType\030\002 \001(" +
      "\0162\t.MailType\"A\n\013apiResponse\022\017\n\007message\030\001" +
      " \001(\t\022\013\n\003OTP\030\002 \001(\005\022\024\n\014responsecode\030\003 \001(\005\"" +
      "9\n\020sentmailResponse\022\017\n\007message\030\001 \001(\t\022\024\n\014" +
      "Responsecode\030\002 \001(\005*)\n\010MailType\022\n\n\006UPDATE" +
      "\020\000\022\021\n\rRESETPASSWORD\020\0012\332\001\n\027RegistrationEm" +
      "ailServer\022B\n\025sendOTPtoExistingUser\022\033.mai" +
      "lRequestforExistingUser\032\014.apiResponse\0228\n" +
      "\020sendOTPTONewUser\022\026.mailRequesttoregiste" +
      "r\032\014.apiResponse\022A\n\024sendregistrationMail\022" +
      "\026.mailRequesttoregister\032\021.sentmailRespon" +
      "seB9\n5com.stackroute.musicmantra.noty5.e" +
      "mailserver.registerP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegisterVerifyied_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegisterVerifyied_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterVerifyied_descriptor,
        new java.lang.String[] { "OTPverified", "Emailid", });
    internal_static_mailRequesttoregister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mailRequesttoregister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mailRequesttoregister_descriptor,
        new java.lang.String[] { "Emailid", });
    internal_static_mailRequestforExistingUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mailRequestforExistingUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mailRequestforExistingUser_descriptor,
        new java.lang.String[] { "Emailid", "MailType", });
    internal_static_apiResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_apiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apiResponse_descriptor,
        new java.lang.String[] { "Message", "OTP", "Responsecode", });
    internal_static_sentmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_sentmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentmailResponse_descriptor,
        new java.lang.String[] { "Message", "Responsecode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
