FROM openjdk:11
EXPOSE 8086
ADD ./target/project1-1.0-SNAPSHOT-jar-with-dependencies.jar project1-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar","project1-1.0-SNAPSHOT-jar-with-dependencies.jar"]