// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailService.proto

package com.stackroute.musicmantra.noty5.emailserver;

public interface bookingDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string userEmail = 2;</code>
   */
  java.lang.String getUserEmail();
  /**
   * <code>string userEmail = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserEmailBytes();

  /**
   * <code>string courseName = 3;</code>
   */
  java.lang.String getCourseName();
  /**
   * <code>string courseName = 3;</code>
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>.google.protobuf.Timestamp time_name = 4;</code>
   */
  boolean hasTimeName();
  /**
   * <code>.google.protobuf.Timestamp time_name = 4;</code>
   */
  com.google.protobuf.Timestamp getTimeName();
  /**
   * <code>.google.protobuf.Timestamp time_name = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeNameOrBuilder();

  /**
   * <code>string sendersEmail = 5;</code>
   */
  java.lang.String getSendersEmail();
  /**
   * <code>string sendersEmail = 5;</code>
   */
  com.google.protobuf.ByteString
      getSendersEmailBytes();

  /**
   * <code>string sendersEmailPassword = 6;</code>
   */
  java.lang.String getSendersEmailPassword();
  /**
   * <code>string sendersEmailPassword = 6;</code>
   */
  com.google.protobuf.ByteString
      getSendersEmailPasswordBytes();
}
