// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailService.proto

package com.stackroute.musicmantra.noty5.emailserver;

/**
 * Protobuf enum {@code bookingtype}
 */
public enum bookingtype
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>confirm = 0;</code>
   */
  confirm(0),
  /**
   * <code>cancel = 1;</code>
   */
  cancel(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>confirm = 0;</code>
   */
  public static final int confirm_VALUE = 0;
  /**
   * <code>cancel = 1;</code>
   */
  public static final int cancel_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static bookingtype valueOf(int value) {
    return forNumber(value);
  }

  public static bookingtype forNumber(int value) {
    switch (value) {
      case 0: return confirm;
      case 1: return cancel;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<bookingtype>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      bookingtype> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<bookingtype>() {
          public bookingtype findValueByNumber(int number) {
            return bookingtype.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return EmailService.getDescriptor().getEnumTypes().get(1);
  }

  private static final bookingtype[] VALUES = values();

  public static bookingtype valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private bookingtype(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bookingtype)
}

