// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailService.proto

package com.stackroute.musicmantra.noty5.emailserver;

public interface bookingDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bookingId = 1;</code>
   */
  int getBookingId();

  /**
   * <code>string bookingtype = 2;</code>
   */
  java.lang.String getBookingtype();
  /**
   * <code>string bookingtype = 2;</code>
   */
  com.google.protobuf.ByteString
      getBookingtypeBytes();
}
