// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailService.proto

package com.stackroute.musicmantra.noty5.emailserver;

public final class EmailService {
  private EmailService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_apiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_apiResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022EmailService.proto\032\037google/protobuf/ti" +
      "mestamp.proto\":\n\013mailRequest\022\016\n\006userId\030\001" +
      " \001(\t\022\033\n\010mailType\030\002 \001(\0162\t.MailType\"A\n\013api" +
      "Response\022\017\n\007message\030\001 \001(\t\022\013\n\003OTP\030\002 \001(\005\022\024" +
      "\n\014responsecode\030\003 \001(\005\"\254\001\n\016bookingDetails\022" +
      "\020\n\010userName\030\001 \001(\t\022\021\n\tuserEmail\030\002 \001(\t\022\022\n\n" +
      "courseName\030\003 \001(\t\022-\n\ttime_name\030\004 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\024\n\014sendersEmail\030" +
      "\005 \001(\t\022\034\n\024sendersEmailPassword\030\006 \001(\t\"<\n\023b" +
      "ookingmailResponse\022\017\n\007message\030\001 \001(\t\022\024\n\014R" +
      "esponsecode\030\002 \001(\005*$\n\010MailType\022\014\n\010REGISTE" +
      "R\020\000\022\n\n\006UPDATE\020\0012n\n\013EmailServer\022)\n\013sendOT" +
      "PMail\022\014.mailRequest\032\014.apiResponse\0224\n\023boo" +
      "kingNotification\022\017.bookingDetails\032\014.apiR" +
      "esponseB0\n,com.stackroute.musicmantra.no" +
      "ty5.emailserverP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_mailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mailRequest_descriptor,
        new java.lang.String[] { "UserId", "MailType", });
    internal_static_apiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_apiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_apiResponse_descriptor,
        new java.lang.String[] { "Message", "OTP", "Responsecode", });
    internal_static_bookingDetails_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bookingDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingDetails_descriptor,
        new java.lang.String[] { "UserName", "UserEmail", "CourseName", "TimeName", "SendersEmail", "SendersEmailPassword", });
    internal_static_bookingmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bookingmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingmailResponse_descriptor,
        new java.lang.String[] { "Message", "Responsecode", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
