// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailService.proto

package com.stackroute.musicmantra.noty5.emailserver;

/**
 * Protobuf type {@code mailRequestforExistingUser}
 */
public  final class mailRequestforExistingUser extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mailRequestforExistingUser)
    mailRequestforExistingUserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use mailRequestforExistingUser.newBuilder() to construct.
  private mailRequestforExistingUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private mailRequestforExistingUser() {
    emailid_ = "";
    mailType_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private mailRequestforExistingUser(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            emailid_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            mailType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EmailService.internal_static_mailRequestforExistingUser_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EmailService.internal_static_mailRequestforExistingUser_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mailRequestforExistingUser.class, Builder.class);
  }

  public static final int EMAILID_FIELD_NUMBER = 1;
  private volatile Object emailid_;
  /**
   * <code>string emailid = 1;</code>
   */
  public String getEmailid() {
    Object ref = emailid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      emailid_ = s;
      return s;
    }
  }
  /**
   * <code>string emailid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmailidBytes() {
    Object ref = emailid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      emailid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAILTYPE_FIELD_NUMBER = 2;
  private int mailType_;
  /**
   * <code>.MailType mailType = 2;</code>
   */
  public int getMailTypeValue() {
    return mailType_;
  }
  /**
   * <code>.MailType mailType = 2;</code>
   */
  public MailType getMailType() {
    @SuppressWarnings("deprecation")
    MailType result = MailType.valueOf(mailType_);
    return result == null ? MailType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmailidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, emailid_);
    }
    if (mailType_ != MailType.UPDATE.getNumber()) {
      output.writeEnum(2, mailType_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmailidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, emailid_);
    }
    if (mailType_ != MailType.UPDATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, mailType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mailRequestforExistingUser)) {
      return super.equals(obj);
    }
    mailRequestforExistingUser other = (mailRequestforExistingUser) obj;

    boolean result = true;
    result = result && getEmailid()
        .equals(other.getEmailid());
    result = result && mailType_ == other.mailType_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMAILID_FIELD_NUMBER;
    hash = (53 * hash) + getEmailid().hashCode();
    hash = (37 * hash) + MAILTYPE_FIELD_NUMBER;
    hash = (53 * hash) + mailType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mailRequestforExistingUser parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailRequestforExistingUser parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailRequestforExistingUser parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailRequestforExistingUser parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailRequestforExistingUser parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailRequestforExistingUser parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailRequestforExistingUser parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailRequestforExistingUser parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailRequestforExistingUser parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mailRequestforExistingUser parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailRequestforExistingUser parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailRequestforExistingUser parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mailRequestforExistingUser prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mailRequestforExistingUser}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mailRequestforExistingUser)
      mailRequestforExistingUserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmailService.internal_static_mailRequestforExistingUser_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmailService.internal_static_mailRequestforExistingUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mailRequestforExistingUser.class, Builder.class);
    }

    // Construct using com.stackroute.musicmantra.noty5.emailserver.mailRequestforExistingUser.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      emailid_ = "";

      mailType_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EmailService.internal_static_mailRequestforExistingUser_descriptor;
    }

    @Override
    public mailRequestforExistingUser getDefaultInstanceForType() {
      return mailRequestforExistingUser.getDefaultInstance();
    }

    @Override
    public mailRequestforExistingUser build() {
      mailRequestforExistingUser result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public mailRequestforExistingUser buildPartial() {
      mailRequestforExistingUser result = new mailRequestforExistingUser(this);
      result.emailid_ = emailid_;
      result.mailType_ = mailType_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mailRequestforExistingUser) {
        return mergeFrom((mailRequestforExistingUser)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mailRequestforExistingUser other) {
      if (other == mailRequestforExistingUser.getDefaultInstance()) return this;
      if (!other.getEmailid().isEmpty()) {
        emailid_ = other.emailid_;
        onChanged();
      }
      if (other.mailType_ != 0) {
        setMailTypeValue(other.getMailTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mailRequestforExistingUser parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mailRequestforExistingUser) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object emailid_ = "";
    /**
     * <code>string emailid = 1;</code>
     */
    public String getEmailid() {
      Object ref = emailid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        emailid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string emailid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailidBytes() {
      Object ref = emailid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        emailid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string emailid = 1;</code>
     */
    public Builder setEmailid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string emailid = 1;</code>
     */
    public Builder clearEmailid() {
      
      emailid_ = getDefaultInstance().getEmailid();
      onChanged();
      return this;
    }
    /**
     * <code>string emailid = 1;</code>
     */
    public Builder setEmailidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailid_ = value;
      onChanged();
      return this;
    }

    private int mailType_ = 0;
    /**
     * <code>.MailType mailType = 2;</code>
     */
    public int getMailTypeValue() {
      return mailType_;
    }
    /**
     * <code>.MailType mailType = 2;</code>
     */
    public Builder setMailTypeValue(int value) {
      mailType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.MailType mailType = 2;</code>
     */
    public MailType getMailType() {
      @SuppressWarnings("deprecation")
      MailType result = MailType.valueOf(mailType_);
      return result == null ? MailType.UNRECOGNIZED : result;
    }
    /**
     * <code>.MailType mailType = 2;</code>
     */
    public Builder setMailType(MailType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      mailType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.MailType mailType = 2;</code>
     */
    public Builder clearMailType() {
      
      mailType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mailRequestforExistingUser)
  }

  // @@protoc_insertion_point(class_scope:mailRequestforExistingUser)
  private static final mailRequestforExistingUser DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mailRequestforExistingUser();
  }

  public static mailRequestforExistingUser getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<mailRequestforExistingUser>
      PARSER = new com.google.protobuf.AbstractParser<mailRequestforExistingUser>() {
    @Override
    public mailRequestforExistingUser parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new mailRequestforExistingUser(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<mailRequestforExistingUser> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<mailRequestforExistingUser> getParserForType() {
    return PARSER;
  }

  @Override
  public mailRequestforExistingUser getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

